root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:Redirect
        route: fos_user_security_login
        permanent: true
#ADMIN
admin_carga_item:
    pattern:  /admin/carga/item
    defaults: { _controller: CademReporteBundle:Admin:cargaitem }
admin_carga_sala:
    pattern:  /admin/carga/sala
    defaults: { _controller: CademReporteBundle:Admin:cargasala }
admin_carga_itemcliente:
    pattern:  /admin/carga/item-cliente
    defaults: { _controller: CademReporteBundle:Admin:cargaitemcliente }
admin_carga_salacliente:
    pattern:  /admin/carga/sala-cliente
    defaults: { _controller: CademReporteBundle:Admin:cargasalacliente }
admin_carga_planoquiebre:
    pattern:  /admin/carga/planograma-quiebre
    defaults: { _controller: CademReporteBundle:Admin:cargaplanoquiebre }
admin_carga_planoprecio:
    pattern:  /admin/carga/planograma-precio
    defaults: { _controller: CademReporteBundle:Admin:cargaplanoprecio }
admin_fileupload:
    pattern:  /admin/fileupload
    defaults: { _controller: CademReporteBundle:Admin:fileupload }
admin_filevalid:
    pattern:  /admin/admin_filevalid
    defaults: { _controller: CademReporteBundle:Admin:filevalid }
admin_fileprocess:
    pattern:  /admin/admin_fileprocess
    defaults: { _controller: CademReporteBundle:Admin:fileprocess }
#DASHBOARD
dashboard_index:
    pattern:  /dashboard
    defaults: { _controller: CademReporteBundle:Dashboard:index }
dashboard_indicadores:
    pattern:  /dashboard/indicadores
    defaults: { _controller: CademReporteBundle:Dashboard:indicadores }
#PRECIO
precio_evolucion_index:
    pattern: /precio/evolucion
    defaults: { _controller: CademReporteBundle:PrecioEvolucion:index } 
precio_evolucion_header:
    pattern:  /precio/evolucion/header
    defaults: { _controller: CademReporteBundle:PrecioEvolucion:header }	
precio_evolucion_body:
    pattern:  /precio/evolucion/body
    defaults: { _controller: CademReporteBundle:PrecioEvolucion:body }	
precio_detalle_index:
    pattern: /precio/detalle
    defaults: { _controller: CademReporteBundle:PrecioDetalle:index } 
precio_detalle_header:
    pattern:  /precio/detalle/header
    defaults: { _controller: CademReporteBundle:PrecioDetalle:header }	
precio_detalle_body:
    pattern:  /precio/detalle/body
    defaults: { _controller: CademReporteBundle:PrecioDetalle:body }	
#QUIEBRE
quiebre_resumen_index:
    pattern: /quiebre/resumen
    defaults: { _controller: CademReporteBundle:QuiebreResumen:index }
quiebre_resumen_evolutivo:
    pattern: /quiebre/resumen/evolutivo
    defaults: { _controller: CademReporteBundle:QuiebreResumen:evolutivo }	
quiebre_resumen_header:
    pattern: /quiebre/resumen/header
    defaults: { _controller: CademReporteBundle:QuiebreResumen:header }		
quiebre_resumen_body:
    pattern: /quiebre/resumen/body
    defaults: { _controller: CademReporteBundle:QuiebreResumen:body }
quiebre_ranking_index:
    pattern:  /quiebre/ranking
    defaults: { _controller: CademReporteBundle:QuiebreRanking:index }
quiebre_ranking_filtros:
    pattern:  /quiebre/ranking/filtros
    defaults: { _controller: CademReporteBundle:QuiebreRanking:filtros }
    methods:  [GET]
quiebre_evolucion_index:
    pattern:  /quiebre/evolucion
    defaults: { _controller: CademReporteBundle:QuiebreEvolucion:index }
quiebre_evolucion_header:
    pattern:  /quiebre/evolucion/header
    defaults: { _controller: CademReporteBundle:QuiebreEvolucion:header }		
quiebre_evolucion_body:
    pattern:  /quiebre/evolucion/body
    defaults: { _controller: CademReporteBundle:QuiebreEvolucion:body }	
quiebre_detalle_index:
    pattern:  /quiebre/detalle
    defaults: { _controller: CademReporteBundle:QuiebreDetalle:index }	
quiebre_detalle_header:
    pattern:  /quiebre/detalle/header
    defaults: { _controller: CademReporteBundle:QuiebreDetalle:header }		
quiebre_detalle_body:
    pattern:  /quiebre/detalle/body
    defaults: { _controller: CademReporteBundle:QuiebreDetalle:body }
quiebre_detalle_excel:
    pattern:  /quiebre/detalle/excel
    defaults: { _controller: CademReporteBundle:QuiebreDetalle:excel }
#RUTAS GENERALES Y AYUDANTES
helper_filtro_region:
    pattern:  /h/filtro/region
    defaults: { _controller: CademReporteBundle:Helper:filtroregion }
    methods:  [GET]
helper_filtro_provincia:
    pattern:  /h/filtro/provincia
    defaults: { _controller: CademReporteBundle:Helper:filtroprovincia }
    methods:  [GET]
#ESTATICAS
privacidad:
    pattern: /privacidad
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'CademReporteBundle:Estaticas:privacidad.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
navegadores_soportados:
    pattern: /navegadores-soportados
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'CademReporteBundle:Estaticas:navegadores.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
