root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:Redirect
        route: dashboard_index
        permanent: true
#ADMIN
admin_carga_item:
    pattern:  /admin/carga/item
    defaults: { _controller: CademReporteBundle:Admin:cargaitem }
admin_carga_sala:
    pattern:  /admin/carga/sala
    defaults: { _controller: CademReporteBundle:Admin:cargasala }
admin_fileupload:
    pattern:  /admin/fileupload
    defaults: { _controller: CademReporteBundle:Admin:fileupload }
admin_filevalid:
    pattern:  /admin/admin_filevalid
    defaults: { _controller: CademReporteBundle:Admin:filevalid }
admin_fileprocess:
    pattern:  /admin/admin_fileprocess
    defaults: { _controller: CademReporteBundle:Admin:fileprocess }
#DASHBOARD
dashboard_index:
    pattern:  /dashboard
    defaults: { _controller: CademReporteBundle:Dashboard:index }
dashboard_indicadores:
    pattern:  /dashboard/indicadores
    defaults: { _controller: CademReporteBundle:Dashboard:indicadores }
#QUIEBRE
quiebre_resumen_index:
    pattern: /quiebre/resumen
    defaults: { _controller: CademReporteBundle:Resumen:index }
quiebre_resumen_evolutivo:
    pattern: /quiebre/resumen/evolutivo
    defaults: { _controller: CademReporteBundle:Resumen:evolutivo }	
quiebre_resumen_header:
    pattern: /quiebre/resumen/header
    defaults: { _controller: CademReporteBundle:Resumen:header }		
quiebre_resumen_body:
    pattern: /quiebre/resumen/body
    defaults: { _controller: CademReporteBundle:Resumen:body }
quiebre_ranking_index:
    pattern:  /quiebre/ranking
    defaults: { _controller: CademReporteBundle:Ranking:index }
quiebre_ranking_filtros:
    pattern:  /quiebre/ranking/filtros
    defaults: { _controller: CademReporteBundle:Ranking:filtros }
    methods:  [GET]
quiebre_evolucion_index:
    pattern:  /quiebre/evolucion
    defaults: { _controller: CademReporteBundle:Evolucion:index }
quiebre_evolucion_header:
    pattern:  /quiebre/evolucion/header
    defaults: { _controller: CademReporteBundle:Evolucion:header }		
quiebre_evolucion_body:
    pattern:  /quiebre/evolucion/body
    defaults: { _controller: CademReporteBundle:Evolucion:body }	
quiebre_detalle_index:
    pattern:  /quiebre/detalle
    defaults: { _controller: CademReporteBundle:Detalle:index }	
quiebre_detalle_header:
    pattern:  /quiebre/detalle/header
    defaults: { _controller: CademReporteBundle:Detalle:header }		
quiebre_detalle_body:
    pattern:  /quiebre/detalle/body
    defaults: { _controller: CademReporteBundle:Detalle:body }
quiebre_detalle_excel:
    pattern:  /quiebre/detalle/excel
    defaults: { _controller: CademReporteBundle:Detalle:excel }
#RUTAS GENERALES Y AYUDANTES
helper_filtro_region:
    pattern:  /h/filtro/region
    defaults: { _controller: CademReporteBundle:Helper:filtroregion }
    methods:  [GET]
helper_filtro_provincia:
    pattern:  /h/filtro/provincia
    defaults: { _controller: CademReporteBundle:Helper:filtroprovincia }
    methods:  [GET]
#ESTATICAS
privacidad:
    pattern: /privacidad
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'CademReporteBundle:Estaticas:privacidad.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
