root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:Redirect
        route: fos_user_security_login
        permanent: true
#ADMIN
admin_carga_item:
    pattern:  /admin/carga/item
    defaults: { _controller: CademReporteBundle:Admin:cargaitem }
admin_carga_sala:
    pattern:  /admin/carga/sala
    defaults: { _controller: CademReporteBundle:Admin:cargasala }
admin_carga_itemcliente:
    pattern:  /admin/carga/item-cliente
    defaults: { _controller: CademReporteBundle:Admin:cargaitemcliente }
admin_carga_salacliente:
    pattern:  /admin/carga/sala-cliente
    defaults: { _controller: CademReporteBundle:Admin:cargasalacliente }
admin_carga_planoquiebre:
    pattern:  /admin/carga/planograma-quiebre
    defaults: { _controller: CademReporteBundle:Admin:cargaplanoquiebre }
admin_carga_planoprecio:
    pattern:  /admin/carga/planograma-precio
    defaults: { _controller: CademReporteBundle:Admin:cargaplanoprecio }
admin_fileupload:
    pattern:  /admin/fileupload
    defaults: { _controller: CademReporteBundle:Admin:fileupload }
admin_filevalid:
    pattern:  /admin/admin_filevalid
    defaults: { _controller: CademReporteBundle:Admin:filevalid }
admin_fileprocess:
    pattern:  /admin/admin_fileprocess
    defaults: { _controller: CademReporteBundle:Admin:fileprocess }
admin_carga_registros:
    pattern:  /admin/carga/registros/{variable}
    defaults: { _controller: CademReporteBundle:Admin:cargaregistro }
    requirements:
        variable:  planoquiebre|planoprecio|itemcliente|salacliente
admin_carga_borrarregistros:
    pattern:  /admin/carga/borrarregistros/{variable}
    defaults: { _controller: CademReporteBundle:Admin:cargaborrarregistro }
    requirements:
        variable:  planoquiebre|planoprecio|itemcliente|salacliente
#DASHBOARD
dashboard_index:
    pattern:  /dashboard
    defaults: { _controller: CademReporteBundle:Dashboard:index }
dashboard_indicadores:
    pattern:  /dashboard/indicadores
    defaults: { _controller: CademReporteBundle:Dashboard:indicadores }
dashboard_map:
    pattern:  /dashboard/map
    defaults: { _controller: CademReporteBundle:Dashboard:map }
#PRECIO
precio_resumen_index:
    pattern: /{variable}/resumen
    defaults: { _controller: CademReporteBundle:PrecioResumen:index, variable: precio }
    requirements:
        variable:  precio
precio_resumen_evolutivo:
    pattern: /{variable}/resumen/evolutivo
    defaults: { _controller: CademReporteBundle:PrecioResumen:evolutivo, variable: precio }
    requirements:
        variable: precio
precio_resumen_header:
    pattern:  /{variable}/resumen/header
    defaults: { _controller: CademReporteBundle:PrecioResumen:header, variable: precio }
    requirements:
        variable:  precio
precio_resumen_body:
    pattern:  /{variable}/resumen/body
    defaults: { _controller: CademReporteBundle:PrecioResumen:body, variable: precio }
    requirements:
        variable:  precio
precio_evolucion_index:
    pattern: /{variable}/evolucion
    defaults: { _controller: CademReporteBundle:PrecioEvolucion:index, variable: precio } 
    requirements:
        variable:  precio
precio_evolucion_header:
    pattern:  /{variable}/evolucion/header
    defaults: { _controller: CademReporteBundle:PrecioEvolucion:header, variable: precio }
    requirements:
        variable:  precio
precio_evolucion_body:
    pattern:  /{variable}/evolucion/body
    defaults: { _controller: CademReporteBundle:PrecioEvolucion:body, variable: precio }
    requirements:
        variable:  precio
precio_detalle_index:
    pattern: /{variable}/detalle
    defaults: { _controller: CademReporteBundle:PrecioDetalle:index, variable: precio }
    requirements:
        variable:  precio
precio_detalle_header:
    pattern:  /{variable}/detalle/header
    defaults: { _controller: CademReporteBundle:PrecioDetalle:header, variable: precio }
    requirements:
        variable:  precio
precio_detalle_body:
    pattern:  /{variable}/detalle/body
    defaults: { _controller: CademReporteBundle:PrecioDetalle:body, variable: precio }
    requirements:
        variable:  precio
precio_resumen_detalle_header:
    pattern: /{variable}/resumen/detalle_header
    defaults: { _controller: CademReporteBundle:PrecioResumen:detalleheader, variable: precio }
    requirements:
        variable:  precio
precio_resumen_detalle_body:
    pattern: /{variable}/resumen/detalle_body
    defaults: { _controller: CademReporteBundle:PrecioResumen:detallebody, variable: precio }
    requirements:
        variable:  precio
precio_detalle_excel:
    pattern:  /{variable}/detalle/excel
    defaults: { _controller: CademReporteBundle:PrecioDetalle:excel, variable: precio }
    requirements:
        variable:  precio
#QUIEBRE
quiebre_resumen_index:
    pattern: /{variable}/resumen
    defaults: { _controller: CademReporteBundle:QuiebreResumen:index, variable: quiebre }
    requirements:
        variable: quiebre
quiebre_resumen_evolutivo:
    pattern: /{variable}/resumen/evolutivo
    defaults: { _controller: CademReporteBundle:QuiebreResumen:evolutivo, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_resumen_header:
    pattern: /{variable}/resumen/header
    defaults: { _controller: CademReporteBundle:QuiebreResumen:header, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_resumen_body:
    pattern: /{variable}/resumen/body
    defaults: { _controller: CademReporteBundle:QuiebreResumen:body, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_resumen_detalle_header:
    pattern: /{variable}/resumen/detalle_header
    defaults: { _controller: CademReporteBundle:QuiebreResumen:detalleheader, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_resumen_detalle_body:
    pattern: /{variable}/resumen/detalle_body
    defaults: { _controller: CademReporteBundle:QuiebreResumen:detallebody, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_ranking_index:
    pattern:  /{variable}/ranking
    defaults: { _controller: CademReporteBundle:QuiebreRanking:index, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_ranking_filtros:
    pattern:  /{variable}/ranking/filtros
    defaults: { _controller: CademReporteBundle:QuiebreRanking:filtros, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_evolucion_index:
    pattern:  /{variable}/evolucion
    defaults: { _controller: CademReporteBundle:QuiebreEvolucion:index, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_evolucion_header:
    pattern:  /{variable}/evolucion/header
    defaults: { _controller: CademReporteBundle:QuiebreEvolucion:header, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_evolucion_body:
    pattern:  /{variable}/evolucion/body
    defaults: { _controller: CademReporteBundle:QuiebreEvolucion:body, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_detalle_index:
    pattern:  /{variable}/detalle
    defaults: { _controller: CademReporteBundle:QuiebreDetalle:index, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_detalle_header:
    pattern:  /{variable}/detalle/header
    defaults: { _controller: CademReporteBundle:QuiebreDetalle:header, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_detalle_body:
    pattern:  /{variable}/detalle/body
    defaults: { _controller: CademReporteBundle:QuiebreDetalle:body, variable: quiebre }
    requirements:
        variable:  quiebre
quiebre_detalle_excel:
    pattern:  /{variable}/detalle/excel
    defaults: { _controller: CademReporteBundle:QuiebreDetalle:excel, variable: quiebre }
    requirements:
        variable:  quiebre
#PRESENCIA
presencia_resumen_index:
    pattern: /{variable}/resumen
    defaults: { _controller: CademReporteBundle:PresenciaResumen:index, variable: presencia }
    requirements:
        variable: presencia
presencia_resumen_detalle_header:
    pattern: /{variable}/resumen/detalle_header
    defaults: { _controller: CademReporteBundle:PresenciaResumen:detalleheader, variable: presencia }
    requirements:
        variable:  presencia
presencia_resumen_detalle_body:
    pattern: /{variable}/resumen/detalle_body
    defaults: { _controller: CademReporteBundle:PresenciaResumen:detallebody, variable: presencia }
    requirements:
        variable:  presencia
presencia_resumen_evolutivo:
    pattern: /{variable}/resumen/evolutivo
    defaults: { _controller: CademReporteBundle:PresenciaResumen:evolutivo, variable: presencia }
    requirements:
        variable: presencia
presencia_resumen_header:
    pattern: /{variable}/resumen/header
    defaults: { _controller: CademReporteBundle:PresenciaResumen:header, variable: presencia }
    requirements:
        variable:  presencia
presencia_resumen_body:
    pattern: /{variable}/resumen/body
    defaults: { _controller: CademReporteBundle:PresenciaResumen:body, variable: presencia }
    requirements:
        variable:  presencia
presencia_ranking_index:
    pattern:  /{variable}/ranking
    defaults: { _controller: CademReporteBundle:PresenciaRanking:index, variable: presencia }
    requirements:
        variable:  presencia
presencia_ranking_filtros:
    pattern:  /{variable}/ranking/filtros
    defaults: { _controller: CademReporteBundle:PresenciaRanking:filtros, variable: presencia }
    requirements:
        variable: presencia
presencia_evolucion_index:
    pattern:  /{variable}/evolucion
    defaults: { _controller: CademReporteBundle:PresenciaEvolucion:index, variable: presencia }
    requirements:
        variable:  presencia
presencia_evolucion_header:
    pattern:  /{variable}/evolucion/header
    defaults: { _controller: CademReporteBundle:PresenciaEvolucion:header, variable: presencia }
    requirements:
        variable: presencia
presencia_evolucion_body:
    pattern:  /{variable}/evolucion/body
    defaults: { _controller: CademReporteBundle:PresenciaEvolucion:body, variable: presencia }
    requirements:
        variable: presencia
presencia_detalle_index:
    pattern:  /{variable}/detalle
    defaults: { _controller: CademReporteBundle:PresenciaDetalle:index, variable: presencia }
    requirements:
        variable: presencia
presencia_detalle_header:
    pattern:  /{variable}/detalle/header
    defaults: { _controller: CademReporteBundle:PresenciaDetalle:header, variable: presencia }
    requirements:
        variable: presencia
presencia_detalle_body:
    pattern:  /{variable}/detalle/body
    defaults: { _controller: CademReporteBundle:PresenciaDetalle:body, variable: presencia }
    requirements:
        variable: presencia
presencia_detalle_excel:
    pattern:  /{variable}/detalle/excel
    defaults: { _controller: CademReporteBundle:PresenciaDetalle:excel, variable: presencia }
    requirements:
        variable: presencia
#RUTAS GENERALES Y AYUDANTES
helper_filtro_region:
    pattern:  /h/filtro/region
    defaults: { _controller: CademReporteBundle:Helper:filtroregion }
    methods:  [GET]
helper_filtro_provincia:
    pattern:  /h/filtro/provincia
    defaults: { _controller: CademReporteBundle:Helper:filtroprovincia }
    methods:  [GET]
#ESTATICAS
privacidad:
    pattern: /static/privacidad
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'CademReporteBundle:Estaticas:privacidad.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
navegadores_soportados:
    pattern: /static/navegadores-soportados
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'CademReporteBundle:Estaticas:navegadores.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400
        private: false
