# cadem_reporte_homepage:
    # pattern:  /
    # defaults: { _controller: CademReporteBundle:Default:index }
# cadem_reporte_indicadores:
    # pattern:  /indicadores
    # defaults: { _controller: CademReporteBundle:Default:indicadores }
root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:Redirect
        route: dashboard_index
        permanent: true
dashboard_index:
    pattern:  /dashboard
    defaults: { _controller: CademReporteBundle:Dashboard:index }
dashboard_indicadores:
    pattern:  /dashboard/indicadores
    defaults: { _controller: CademReporteBundle:Dashboard:indicadores }
resumen_index:
    pattern: /resumen
    defaults: { _controller: CademReporteBundle:Resumen:index }
resumen_evolutivo:
    pattern: /resumen/evolutivo
    defaults: { _controller: CademReporteBundle:Resumen:evolutivo }	
ranking_index:
    pattern:  /ranking
    defaults: { _controller: CademReporteBundle:Ranking:index }
