root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:Redirect
        route: dashboard_index
        permanent: true
dashboard_index:
    pattern:  /dashboard
    defaults: { _controller: CademReporteBundle:Dashboard:index }
dashboard_indicadores:
    pattern:  /dashboard/indicadores
    defaults: { _controller: CademReporteBundle:Dashboard:indicadores }
resumen_index:
    pattern: /resumen
    defaults: { _controller: CademReporteBundle:Resumen:index }
resumen_evolutivo:
    pattern: /resumen/evolutivo
    defaults: { _controller: CademReporteBundle:Resumen:evolutivo }	
resumen_periodo:
    pattern: /resumen/periodo
    defaults: { _controller: CademReporteBundle:Resumen:periodo }	
resumen_tabla:
    pattern: /resumen/tabla
    defaults: { _controller: CademReporteBundle:Resumen:tabla }	
ranking_index:
    pattern:  /ranking
    defaults: { _controller: CademReporteBundle:Ranking:index }
ranking_filtros:
    pattern:  /ranking/filtros
    defaults: { _controller: CademReporteBundle:Ranking:filtros }
    methods:  [GET]
detalle_index:
    pattern:  /detalle
    defaults: { _controller: CademReporteBundle:Detalle:index }
evolucion_index:
    pattern:  /evolucion
    defaults: { _controller: CademReporteBundle:Evolucion:index }
evolucion_tabla:
    pattern:  /evolucion/tabla
    defaults: { _controller: CademReporteBundle:Evolucion:tabla }	
#RUTAS GENERALES Y AYUDANTES
helper_filtro_region:
    pattern:  /h/filtro/region
    defaults: { _controller: CademReporteBundle:Helper:filtroregion }
    methods:  [GET]
helper_filtro_provincia:
    pattern:  /h/filtro/provincia
    defaults: { _controller: CademReporteBundle:Helper:filtroprovincia }
    methods:  [GET]
