# cadem_reporte_homepage:
    # pattern:  /
    # defaults: { _controller: CademReporteBundle:Default:index }
# cadem_reporte_indicadores:
    # pattern:  /indicadores
    # defaults: { _controller: CademReporteBundle:Default:indicadores }
dashboard_index:
    pattern:  /dashboard
    defaults: { _controller: CademReporteBundle:Dashboard:index }
dashboard_indicadores:
    pattern:  /dashboard/indicadores
    defaults: { _controller: CademReporteBundle:Dashboard:indicadores }
cadem_reporte_resumen:
    pattern: /resumen
    defaults: { _controller: CademReporteBundle:Resumen:index }

