parameters:
#    cadem_reporte.example.class: Cadem\ReporteBundle\Example

services:
#    cadem_reporte.example:
#        class: %cadem_reporte.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    cadem_reporte.request_listener:
        class: Cadem\ReporteBundle\EventListener\RequestListener
        arguments: [@router, @security.context, @cadem_reporte.helper.cliente]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest  }
    cadem_reporte.response_listener:
        class: Cadem\ReporteBundle\EventListener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse  }
    # cadem_reporte.controller_listener:
    #     class: Cadem\ReporteBundle\EventListener\ControllerListener
    #     arguments: [@router, @security.context, @cadem_reporte.helper.cliente, @debug.controller_resolver]
    #     tags:	
    #         - { name: kernel.event_listener, event: kernel.controller, method: onKernelController  }		
    cadem_reporte.twig.rst_extension:
        class: Cadem\ReporteBundle\Twig\RstExtension
        tags:
            - { name: twig.extension }
    cadem_reporte.helper.salasmedidas:
        class: Cadem\ReporteBundle\Helper\SalasMedidasHelper
        arguments:
            entityManager: @doctrine.orm.entity_manager
            security: @security.context
            medicion: @cadem_reporte.helper.medicion
            total_salas_name: "%total_salas_name%"
    cadem_reporte.helper.medicion:
        class: Cadem\ReporteBundle\Helper\MedicionHelper
        arguments:
            entityManager: @doctrine.orm.entity_manager
            security: @security.context
    cadem_reporte.helper.cliente:
        class: Cadem\ReporteBundle\Helper\ClienteHelper
        arguments:
            entityManager: @doctrine.orm.entity_manager
            security: @security.context			
    cadem_reporte.helper.phpexcel:
        class: Cadem\ReporteBundle\Helper\PHPExcelHelper
        arguments:
            entityManager: @doctrine.orm.entity_manager
            security: @security.context
            medicion: @cadem_reporte.helper.medicion
            session: @session
    cadem_reporte.authentication.login_success_handler:
        class: Cadem\ReporteBundle\EventListener\LoginSuccessHandler
        arguments:  [@router, @security.context]
