parameters:
#    cadem_reporte.example.class: Cadem\ReporteBundle\Example

services:
#    cadem_reporte.example:
#        class: %cadem_reporte.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    # cadem_reporte.interactive_login:
        # class: Cadem\ReporteBundle\EventListener\LastLoginListener
        # arguments: [@fos_user.user_manager, @router]
        # tags:
            # - { name: kernel.event_subscriber  }
    cadem_reporte.request_listener:
        class: Cadem\ReporteBundle\EventListener\RequestListener
        arguments: [@router, @security.context]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest  }
    cadem_reporte.response_listener:
        class: Cadem\ReporteBundle\EventListener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse  }
    cadem_reporte.twig.rst_extension:
        class: Cadem\ReporteBundle\Twig\RstExtension
        tags:
            - { name: twig.extension }
    cadem_reporte.helper.salasmedidas:
        class: Cadem\ReporteBundle\Helper\SalasMedidasHelper
        arguments:
            entityManager: @doctrine.orm.entity_manager
            security: @security.context
    cadem_reporte.helper.medicion:
        class: Cadem\ReporteBundle\Helper\MedicionHelper
        arguments:
            entityManager: @doctrine.orm.entity_manager
            security: @security.context