parameters:
#    cadem_reporte.example.class: Cadem\ReporteBundle\Example

services:
#    cadem_reporte.example:
#        class: %cadem_reporte.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    # cadem_reporte.interactive_login:
        # class: Cadem\ReporteBundle\EventListener\LastLoginListener
        # arguments: [@fos_user.user_manager, @router]
        # tags:
            # - { name: kernel.event_subscriber  }
    cadem_reporte.request_listener:
        class: Cadem\ReporteBundle\EventListener\RequestListener
        arguments: [@router, @security.context]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest  }
    